In [ ]:
# CELL 1: RUN THIS FIRST
print("Initiating Environment Clean & Install...")
!pip install -qU trl transformers unsloth datasets
!pip uninstall -y wandb
print("\n[SYSTEM ALERT]: Installation complete.")
print("CRITICAL STEP: You MUST click 'Runtime' -> 'Restart session' at the top of the screen before running Cell 2.")

Initiating Environment Clean & Install...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 432.3/432.3 kB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 115.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 44.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 37.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.5/376.5 kB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 114.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 120.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.9/181.9 kB 18.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 110.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 kB 25.7 MB/s eta 0:00:00
Found existing installation: wandb 0.25.0
Uninstalling wandb-0.25.0:
  Successfully uninstalled wandb-0.25.0

[SYSTEM ALERT]: Installation complete.
CRITICAL STEP: You MUST click 'Runtime' -> 'Restart session' at the top of the screen before running Cell 2.

In [ ]:
import os
import sys

# --- 1. AUTOMATED DEPENDENCY INSTALLATION ---
try:
    import unsloth
    import trl
    import datasets
    print("[SYSTEM LOG]: All libraries present.")
except ImportError:
    print("[SYSTEM LOG]: Missing dependencies detected. Initiating automated install...")
    os.system("pip uninstall -y wandb")
    os.system("pip install --no-deps trl transformers datasets")
    os.system("pip install unsloth")
    print("[SYSTEM LOG]: Installation complete. Restarting Python kernel...")
    os.execv(sys.executable, ['python'] + sys.argv)

# --- 2. CORE IMPORTS & WANDB SUPPRESSION ---
import re
import torch
from datasets import load_dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from trl import GRPOConfig, GRPOTrainer

os.environ["WANDB_DISABLED"] = "true"

# --- 3. GOOGLE DRIVE MOUNTING ---
try:
    from google.colab import drive
    drive.mount('/content/drive')
    base_dir = '/content/drive/MyDrive/AI_Reasoning_Project'
    os.makedirs(base_dir, exist_ok=True)
    print("\n[SYSTEM LOG]: Google Drive mounted successfully.")
except ImportError:
    print("\n[SYSTEM WARNING]: Not running in Colab. Using local directory.")
    base_dir = './AI_Reasoning_Project'
    os.makedirs(base_dir, exist_ok=True)

# --- 4. CORE BRAIN INITIALIZATION ---
max_seq_length = 1024
lora_rank = 16

print("Loading base model in 4-bit precision...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=max_seq_length,
    load_in_4bit=True,
    fast_inference=False,
    max_lora_rank=lora_rank,
    gpu_memory_utilization=0.6,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=lora_rank,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

# --- 5. THE TRAINING ENVIRONMENT (MATHEMATICS) ---
print("Downloading GSM8K Mathematics Dataset...")
dataset = load_dataset("openai/gsm8k", "main", split="train")

SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

def format_data(example):
    answer = example["answer"].split("#### ")[-1]
    return {
        "prompt": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": example["question"]}
        ],
        "ground_truth": answer
    }

dataset = dataset.map(format_data)

# --- 6. THE REWARD SYSTEM ---
def extract_xml_answer(text: str) -> str:
    try:
        answer = text.split("<answer>")[-1]
        return answer.split("</answer>")[0].strip()
    except:
        return ""

def correctness_reward(completions, ground_truth, **kwargs):
    responses = [completion[0]["content"] for completion in completions]
    extracted_responses = [extract_xml_answer(r) for r in responses]
    return [1.0 if r == gt else 0.0 for r, gt in zip(extracted_responses, ground_truth)]

def format_reward(completions, **kwargs):
    responses = [completion[0]["content"] for completion in completions]
    pattern = r"<reasoning>.*?</reasoning>\\s*<answer>.*?</answer>"
    return [0.5 if re.search(pattern, r, re.DOTALL) else 0.0 for r in responses]

# --- 7. THE REINFORCEMENT LEARNING LOOP ---
print("Configuring GRPO Reinforcement Loop...")
checkpoint_dir = os.path.join(base_dir, "grpo_reasoning_checkpoints")

training_args = GRPOConfig(
    use_vllm=False,
    learning_rate=5e-6,
    adam_beta1=0.9,
    adam_beta2=0.99,
    weight_decay=0.1,
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    optim="paged_adamw_8bit",
    logging_steps=1,
    bf16=is_bfloat16_supported(),
    fp16=not is_bfloat16_supported(),
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    num_generations=4,
    max_prompt_length=256,
    max_completion_length=max_seq_length - 256,
    max_steps=300,
    output_dir=checkpoint_dir,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=3,
    report_to="none"
)

trainer = GRPOTrainer(
    model=model,
    reward_funcs=[correctness_reward, format_reward],
    args=training_args,
    train_dataset=dataset,
)

# --- 8. RESUME AND TRAIN ---
print("\nInitiating Training Protocol...")
try:
    trainer.train(resume_from_checkpoint=True)
    print("[SYSTEM LOG]: Resumed training from checkpoint.")
except (ValueError, TypeError, KeyError):
    print("[SYSTEM LOG]: Starting fresh training loop.")
    trainer.train()

# --- 9. SAVE THE FINAL MODEL ---
final_model_dir = os.path.join(base_dir, "final_reasoning_model")
model.save_pretrained(final_model_dir)
tokenizer.save_pretrained(final_model_dir)
print(f"\n[SYSTEM LOG]: Final weights stored at: {final_model_dir}")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
[SYSTEM LOG]: All libraries present.
Mounted at /content/drive

[SYSTEM LOG]: Google Drive mounted successfully.
Loading base model in 4-bit precision...
==((====))==  Unsloth 2026.2.1: Fast Qwen2 patching. Transformers: 4.57.6.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/1.53G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/270 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Unsloth 2026.2.1 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Downloading GSM8K Mathematics Dataset...

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

Configuring GRPO Reinforcement Loop...

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

Initiating Training Protocol...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7,473 | Num Epochs = 1 | Total steps = 300
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

[SYSTEM LOG]: Resumed training from checkpoint.

[SYSTEM LOG]: Final weights stored at: /content/drive/MyDrive/AI_Reasoning_Project/final_reasoning_model